### ISSUE TITLE
Use GET Parameters to preserve state

### ISSUE THREAD

**Issue by imbrucy** [Asmor/5e-monsters#1]
Being able to preserve page state, i.e. encounters you have built, with nothing more then a link would be extremely useful.  Just adding a few get parameters to set player count, player level, and a listing of monsters would make it easy to open and modify previous encounters without having to fill out all the details over again.

**Comment by Asmor** [comment]
Thanks for the suggestion!

How do you envision yourself actually using this feature? E.g. is it so you can work on stuff later, pull it up at the table, etc?

**Comment by imbrucy** [comment]
That would be the main use, but also just to be able to pull up a previously planned encounter to modify it.  For example if I had planned something previously that they didn't end up doing I could pull it up and add a few new monsters to account for a higher level they are when they do it later.

**Comment by Asmor** [comment]
Closing this out. I don't recall if this issue predates the localStorage saving built into the app, but in any case this isn't something I'm likely to implement.
