### ISSUE TITLE
Improving the template.

### ISSUE THREAD

**Issue by Mackachoo** [Asmor/5e-monsters#101]
I'm not sure if you can add this directly to spread sheets but you could add this bit of javascript to make the fid easier to make. Alternatively you could just copy and paste it into the script editor.

function fidGenerator(input,source) {
  var start = source.concat(".");
  var end = ((input.toLowerCase()).replace(/'/g , "")).replace(/\s/g , "-");
  var output = start.concat(end);
  return output;
}

I'm sure sure it could be optimised (the middle bit is terrible) but I've never used javascript before. 

Then in the template it's just put " =fidGenerator(B1,"source") " in A1.

**Comment by Asmor** [comment]
IDs are used internally as keys, and must remain constant even if the name changes (e.g. fixing typos). Programattic creation of IDs would work initially, but it would have to be static thereafter... There's a lot of potential for this causing issues if e.g. someone left an ID as dynamically generated and then changed the name.

Thus, will not be implementing this.
