### ISSUE TITLE
Adventurers League and DMs Guild Adept Content

### ISSUE THREAD

**Issue by Lexaire** [Asmor/5e-monsters#103]
Hello! When balancing encounters for Adventurers League (AL), DMs are restricted to AL legal content which includes all the regular sources on KFC but also the AL adventures and certain DMs Guild Adept content. I think it would be useful to have these extra monsters in KFC for AL DMs.

I am not sure how best to distinguish them as Sources. There are a few general categories: CCC adventures, 7 seasons of AL adventures, DMs Guild Adept content. DMsGuild https://www.dmsguild.com/product/208178/DD-Adventurers-League-Players-Pack has a file Adventurers_League_Content_Catalogue_v7.03a.pdf with a listing of all the AL legal content which might help with coming up with Sources.

Using a source for every adventure product would add over 100 sources. Using a source for CCC + each season + AL legal DMs Guild Adept would add 9 Sources. Using one for CCC, one for WotC AL adventures, and one for AL legal DMs Guild Adept content would add 3 Sources. I tentatively went with the latter. On DMs Guild there are three types of content: Third Party content, DMs Guild Adept Content, and DMs Guild Adept Content which has been made AL legal. Not all DMs Guild Adept Content is legal for use in AL - only the stuff they've added to that Content Catalogue.

I made a sheet with the monsters from various AL content. Please let me know if these can be added to KFC, and what Sources and references I should use. Thanks!

https://docs.google.com/spreadsheets/d/1MoASrzOS5Ex12-34EN3pgXvQd2Wq6oH4CdJ6xf6CmnY/

**Comment by Asmor** [comment]
Thanks for the suggestion. I'm going to have to think about this. In the mean time you should be able to use the sheet you made as a custom content source. It might be a while before I address this. My apologies.

**Comment by cfi2017** [comment]
Alternatively, you could self host a version of KFC and add your own content to that. That way, you could have AL DMs use that version of KFC while not adding unofficial, not necessarily fully canon monsters to the official KFC instance.

**Comment by Asmor** [comment]
Thanks for working on this. I've decided I don't want to add it into the default sheets, however I'd absolutely recommend sharing the sheet with other Adventurer's League DMs so they can import it themselves.

Actually, it would be neat some time in the future to have a way of cataloging "optional" sources like this that people could add. Maybe some day...

**Comment by Asmor** [comment]
Hi! Please consider adding this content to [this reddit thread](https://www.reddit.com/r/asmor/comments/9dpyxv/list_of_communityadded_kfc_content/). I intend to use this thread as a place for the community to submit content they've created, and for users to come and find content that might be of interest to them.

For an explanation about this change, please see [Why is KFC no longer accepting user-submitted content?](https://github.com/Asmor/5e-monsters/blob/master/README.md#why-is-kfc-no-longer-accepting-user-submitted-content) in the README.
