### ISSUE TITLE
Lost Mine of Phandelver exclusives

### ISSUE THREAD

**Issue by Prowler64** [Asmor/5e-monsters#106]
Hi.
I've added the exclusive creatures from Lost Mine of Phandelver.
https://docs.google.com/spreadsheets/d/1rnF0Fx0zSoBgxuwQba4l5J_O73OC_fDXlLgrCXz_QvQ

All of the regular creatures that appear in the adventure would need to be updated to include Lost Mine.

**Comment by Asmor** [comment]
After contemplating #103, I've decided I'm going to be a bit more picky about what sources I put into the main lists. I won't be adding the Lost Mines. Sorry.

**Comment by Asmor** [comment]
Hi! Please consider adding this content to [this reddit thread](https://www.reddit.com/r/asmor/comments/9dpyxv/list_of_communityadded_kfc_content/). I intend to use this thread as a place for the community to submit content they've created, and for users to come and find content that might be of interest to them.

For an explanation about this change, please see [Why is KFC no longer accepting user-submitted content?](https://github.com/Asmor/5e-monsters/blob/master/README.md#why-is-kfc-no-longer-accepting-user-submitted-content) in the README.
