### ISSUE TITLE
Book of Beautiful Horrors Additions

### ISSUE THREAD

**Issue by Coenani** [Asmor/5e-monsters#108]
I am trying to add the Monsters from the Book of Beautiful Horrors as a community project to KFC. If anyone is willing/able to help me, I am working in this file:
https://docs.google.com/spreadsheets/d/1hjVFiRCsEaUVyfo1yanH6Fx8ss5qm5VsMmgET6nbtgA/edit#gid=0

This is the version of the book that I am using, also found in the sources.
https://www.reddit.com/r/UnearthedArcana/comments/80i3p6/book_of_beautiful_horrors_update_18_170_pages_of/

**Comment by rexthepig** [comment]
I'd be happy to help, if you still need any.

**Comment by Coenani** [comment]
That would be great! I try to do a few monsters every day to finally finish this. I mostly have problems with the environments, since I am not familiar enough with the monsters themselves to easily fill that in.

**Comment by Coenani** [comment]
I just finished adding all of the CR, sizes, allignments, legendary tags and page numbers.
The only things left to do are the environments!

**Comment by Coenani** [comment]
@Asmor It should be completed now! All monster have the appropriate tags and it has been put through the Sheet Checker.

**Comment by rexthepig** [comment]
Oops, I was too late!
You clearly had it under control anyway, thanks for doing this though, I really liked the Book of Beautiful Horrors and intend to use it in the future, so this will be a great help.

**Comment by miniboes** [comment]
Guess I should have checked here before i started doing it myself. Thanks a lot though, Coenani! Anyway, @Asmor any update on when/whether this is going to be added? It's not on BoH5e, but BoH5e has been barren for a while and doesn't deal with compendiums this size. It's on the curated list of /r/unearthedarcana, the mods of which overlap with the critics on boh5e.

**Comment by Coenani** [comment]
@miniboes For now you can add the following code as a manual entry: 1hjVFiRCsEaUVyfo1yanH6Fx8ss5qm5VsMmgET6nbtgA

It's not optimal, but works until it might be added by Asmor.

**Comment by Asmor** [comment]
Hi! Please consider adding this content to [this reddit thread](https://www.reddit.com/r/asmor/comments/9dpyxv/list_of_communityadded_kfc_content/). I intend to use this thread as a place for the community to submit content they've created, and for users to come and find content that might be of interest to them.

For an explanation about this change, please see [Why is KFC no longer accepting user-submitted content?](https://github.com/Asmor/5e-monsters/blob/master/README.md#why-is-kfc-no-longer-accepting-user-submitted-content) in the README.
