### ISSUE TITLE
Divide encounter XP by party size

### ISSUE THREAD

**Issue by kp-rabbit** [Asmor/5e-monsters#111]
Hey, I use your site all the time for my campaign and I always have to manually divide the Total XP by the party size when calculating rewards. It would be a nice QoL change if the XP totals area also included an "individual XP" field that simply divides the total XP by party size.

Thanks for all of your hard work!

**Comment by elsoybean** [comment]
Submitted PR #143

**Comment by Asmor** [comment]
@elsoybean has implemented this. It will be live in a bit.
