### ISSUE TITLE
Critter Compendium

### ISSUE THREAD

**Issue by Threeshades** [Asmor/5e-monsters#115]
https://docs.google.com/spreadsheets/d/1y1S8mjSiiSotBWaRtkJtioANqRfPh36Tjbz4Sb_vd9s/edit?usp=sharing

Hi everyone, this is the completed spreadsheet for the Critter Compendium available on DMs Guild. I'm the original author and lots of people asked me to make the content available for Fobold Fight Club. I haven't put this content through best of homebrew because i figured the ratings and bestseller medal speak for themselves. See below

http://www.dmsguild.com/product/210151/Critter-Compendium

**Comment by Asmor** [comment]
There are a large number of errors which need to be resolved before I can add this.

Paste that link to the sheet into the sheet checker and it will tell you what needs to be fixed.

http://kobold.club/5e-monsters/sheet-check.html

**Comment by Threeshades** [comment]
Ah thanks for the headsup i remember now, i tried to check the doc quite awhile ago and it wouldnt work at all. Working to iron everything out.

EDIT:
I'm through with all but one, which im not sure how to, or if I have to adress. That is

> Missing source from monster list, or duplicated source: Critter Compendium

**Comment by hushukyo** [comment]
I'm glad i checked to see if this was started! I think the conflict is coming from the source column. I'm still really new to this, but i believe it needs a page number for the creatures stats. 

If you'll grant me access, I can go through and add the page numbers over the next few days so hopefully we can get this badmama jama approved. Great book by the way!

**Comment by Threeshades** [comment]
Thanks for the pointer, hushukyo, and thank you for the praise. I added the page numbers myself and now it all checks out.

**Comment by Asmor** [comment]
This has been added. Thanks for persevering!
