### ISSUE TITLE
Long source names can cause alignment issues on medium and small screen widths

### ISSUE THREAD

**Issue by Asmor** [Asmor/5e-monsters#117]
Long sources like the Princes of the Apocalypse Online Supplement can cause the fields in the encounter manager to be pushed undesirably

![image](https://user-images.githubusercontent.com/2127204/39735342-28c336a8-5249-11e8-8b69-1bf86457215f.png)

**Comment by snafuy** [comment]
Adding a max-width to .current-encounter--monster-source fixes it.
