### ISSUE TITLE
Add monsters from Quests of Doom Volume 1 and Volume 2

### ISSUE THREAD

**Issue by vinternet** [Asmor/5e-monsters#122]
I created a spreadsheet with the original creatures and MM variant creatures from Quests of Doom Volume 1 and Quests of Doom Volume 2, from Frog God Games.
Spreadsheet is here: [https://docs.google.com/spreadsheets/d/1WnCkADiqG6kbL2i8cnVAiq-z2JkDPhiFHkbU-tP-cvE/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1WnCkADiqG6kbL2i8cnVAiq-z2JkDPhiFHkbU-tP-cvE/edit?usp=sharing)
Sheet checker shows no errors.

I had to apply a very slight amount of editorial when a monster listing in one of the adventure books was missing information (i.e. calculating CR, saying 'unaligned', or interpreting the environment) but not too much.
If this works out I can also work on Quests of Doom 2.

**Comment by Asmor** [comment]
This has been added. Thanks!
