### ISSUE TITLE
Add Monsters from Mordenkainen's Tome of Foes

### ISSUE THREAD

**Issue by lukemortora01** [Asmor/5e-monsters#123]
I don't see any open issue for this so I figured I'd make a start as soon as I can.

Anyone is free to contribute to the spreadsheet here if they also have a copy of this book:
https://docs.google.com/spreadsheets/d/1U2ibmtgTXEM2kruEQ6_r4fl5KhCnxeODXbw2BfoT_RQ/edit?usp=sharing

**Comment by lukemortora01** [comment]
~~note: am noting which creature have lairs, will go back to duplicate these records and add the non-lair versions as well (as a result, CR for lair creatures will not be accurate yet). Will do more in-depth reading of each monster to decide which environments they belong in - focusing on the main data entry first and foremost.~~

~~EDIT: any creature which has a CR adjustment for lairs now has its own record. Main data entry is complete, just the environment tags to go now.~~

**Comment by lukemortora01** [comment]
Quest completed: All data has now been added. KFC sheet checker says we're good to go. 

I get the impression I need to raise a pull request, but i'm not yet GitHub savvy, so i'll wait for Asmor-senpai to notice my issue and read this comment. Hi Asmor! Let me know if this sheet needs any additional work.

**Comment by Asmor** [comment]
This has been added. Thanks!

FYI, no pull request is needed. Pull requests are for when you're making modifications to the code.
