### ISSUE TITLE
Add Monsters From Nerzugal's Dungeon Master Toolkit 2 / Fixing Nerzugal's Extended Bestiary

### ISSUE THREAD

**Issue by Nerzugal** [Asmor/5e-monsters#124]
Nerzugal Role-Playing released a new book with 100+ new monsters that are ready to be added. It also appears the first half of the creatures from Nerzugal's Extended Bestiary were removed, so I created a new full list to be added. We should be able to clean remove the old "neb" rows and replace them with the ones in this new spreadsheet.

Here is a link to the complete, tested spreadsheet:
https://docs.google.com/spreadsheets/d/10M5gUDZQIj2ytGCeS2ZsxqqoxcURur1asQ_qAyl95_A/edit?usp=sharing

**Comment by Asmor** [comment]
Thanks! I've added these to KFC.

I've run into a slight problem while adding. There were several duplicates that differed in CR, and I don't know which is the correct one. Could you please tell me the correct CRs for each of the following:

neb.azer-magma-shaman
neb.deadly-hunter
neb.haste-devil
neb.mysterious-starcaller
neb.mystic-spellblade
neb.necromancer
neb.radiant-stalker

**Comment by Nerzugal** [comment]
Yep, sorry about that. Some of the values got messed up when I copied and
pasted them over. Here are the values:

neb.azer-magma-shaman - CR 3
neb.deadly-hunter - CR 5
neb.haste-devil - CR 5
neb.mysterious-starcaller - CR 9
neb.mystic-spellblade - CR 5
neb.necromancer - CR 3
neb.radiant-stalker - CR 5


Thank you so much!

**Comment by Asmor** [comment]
Thanks, I've removed the bad duplicates. This should be all set now.
