### ISSUE TITLE
Add monsters from Monsters of the Guild

### ISSUE THREAD

**Issue by kevinaalfonso** [Asmor/5e-monsters#125]
I started working on this today. If I add 10 monsters a day, it should be done some time next week. 

https://docs.google.com/spreadsheets/d/1_kvurAnkLYVEsJZxWJ2AXSzSy05usDQAnXuNyAkKpT8/edit?usp=sharing

**Comment by hushukyo** [comment]
Ill help! Ive never done anything like this before so you might need to double check, but from what i can see im just acting like a data monkey :)

**Comment by kevinaalfonso** [comment]
It is complete. Everything is up to date. A few changes were made (underdark-->underground, hill-->grassland, underwater-->aquatic)

**Comment by Asmor** [comment]
This has been added. Thanks!
