### ISSUE TITLE
Addition: Spectators 

### ISSUE THREAD

**Issue by GemWitch** [Asmor/5e-monsters#130]
https://docs.google.com/spreadsheets/d/1rH_bynzW6Ba3GFyYV8ea1UDgP0pp75MRashj_Jgf8zM/edit?usp=sharing

I was looking to see how my friends would roughly do against a Spectator, and didn't see one so I decided to add the one from the monster manual!

**Comment by Coenani** [comment]
Can you verify that you don't have certain typings selected by accident, since I can see it while searching for it. Do you have the appropriate sources selected?

**Comment by GemWitch** [comment]
@Coenani Apparently I had filters I was unaware of, thankyou for reminding me! I'll close this.
