### ISSUE TITLE
Warn users about filtered results

### ISSUE THREAD

**Issue by Asmor** [Asmor/5e-monsters#131]
A lot of support/missing content requests come from the user having some filters enabled. Would be nice if there was something like "50 results not shown due to active filters" or something like that.

I haven't looked at how the filtering works in a while, so this may not actually be feasible or may be quite difficult.

My thought is that this would only let you know that some monsters _which matched a search_ were filtered out. So if you had filters turned on and your search field is empty, nothing is shown.

So for example, right now if you search for `/\bcat\b`, there are 8 results. 5 of them are beasts, and the other 3 are not. So if you had it set to show only beasts, this message would say "3 results not shown due to active filters" (or whatever verbiage is settled on).

**Comment by elsoybean** [comment]
Took a crack at this: https://github.com/Asmor/5e-monsters/pull/142

**Comment by Asmor** [comment]
@elsoybean has implemented this. It will be live in a bit.
