### ISSUE TITLE
Add Big Book of Zombies, Goblin Warbands, Limitless Monsters & Dark Souls Compendium

### ISSUE THREAD

**Issue by Coenani** [Asmor/5e-monsters#133]
I created 2 extra indices for KFC.

https://docs.google.com/spreadsheets/d/13Ye-J4k9LRhI39J9tSlLQCWj3gIGouKB3_dHFtfaXDQ/edit#gid=1857923629

https://docs.google.com/spreadsheets/d/1eQQGz4fQ4yhONNn8W7YVX6uzGxTMGPGlt9GGBPszFwQ/edit#gid=0

The first one contains the Big Book of Zombies, Limitless Monsters and Goblin Warbands (all 3rd party) and the 2nd one contains the Dark Souls Compendium (Community).

I hope that at least the first one can be added to KFC.

**Comment by Asmor** [comment]
Thanks, I've added these to the community content thread on reddit: https://www.reddit.com/r/asmor/comments/9dpyxv/list_of_communityadded_kfc_content/e5osvxk/
