### ISSUE TITLE
Lost Mine of Phandelver Monsters

### ISSUE THREAD

**Issue by sontanon** [Asmor/5e-monsters#135]
These are the 5 monsters unique to the LMoP starter set:

* Evil mage (CR 1)
* Mormesk the Wraith (CR 3)
* Nezznar the Black Spider (CR 2)
* Redbrand Ruffian (CR 1/2)
* Sildar Hallwinter (CR 1)

https://docs.google.com/spreadsheets/d/1I6t02fTh3-76SFVvfbkf--zKOTrpKfN_24004gfNZKE/edit?usp=sharing

**Comment by Asmor** [comment]
This has also been added by Prowler64 on reddit here: https://www.reddit.com/r/asmor/comments/9dpyxv/list_of_communityadded_kfc_content/e5j9gd7/

I haven't checked if your two sheets are identical or if there are any differences, but feel free to post this in that thread.
