### ISSUE TITLE
Beasts of The Jungle Rot (Adventures League Legal/WOTC) Complete Version

### ISSUE THREAD

**Issue by Thelight00001** [Asmor/5e-monsters#137]
It was still coming up with errors that I had no idea how to fix.

https://docs.google.com/spreadsheets/d/e/2PACX-1vS5kGJi3ui0SyGqDz9FOaTNMxbX7cuKUu5U_cF5gAHhNohzrDi__lfAmBXQrz3fAqxxgpiwQ5MDeayw/pubhtml

http://www.dmsguild.com/product/220567/Beasts-of-the-Jungle-Rot

**Comment by Asmor** [comment]
Thanks for the submission, but I'm not accepting community content. See [here](https://github.com/Asmor/5e-monsters#contributing-community-content) for details.

Also, the reason it's failing is because you have spaces after the names of those monsters.

**Comment by Thelight00001** [comment]
I see. You should add to the FAQ what community created content and what wizards published content means to you. 

It can be confusing for people since Adventures League is owned by Wizards. And things published in AL are copyrighted by WOTC. Although there is no hardcover release. So it would save people like me time in the future if you note some wizards material is considered community content.

**Comment by Asmor** [comment]
Hi! Please consider adding this content to [this reddit thread](https://www.reddit.com/r/asmor/comments/9dpyxv/list_of_communityadded_kfc_content/). I intend to use this thread as a place for the community to submit content they've created, and for users to come and find content that might be of interest to them.

For an explanation about this change, please see [Why is KFC no longer accepting user-submitted content?](https://github.com/Asmor/5e-monsters/blob/master/README.md#why-is-kfc-no-longer-accepting-user-submitted-content) in the README.
