### ISSUE TITLE
Add Imaginary Monsters & Versatile NPC's 

### ISSUE THREAD

**Issue by miniboes** [Asmor/5e-monsters#138]
Here's two excellent homebrew monster compendiums (both of which are on the curated list of /r/unearthedarcana). Would be awesome if you'd consider adding them to the site!

**Imaginary Monsters by IrishBandit**
KoboldFC Sheet: 
<https://docs.google.com/spreadsheets/d/18Snren-eqwUSQGp9leRXoxbowFciXTXIQFr_IgzJuik/edit?usp=sharing>
PDF Source: 
<https://drive.google.com/file/d/0B5ttoyMfsaC7MmJfSWJzbDQtbm8/view>

**Versatile NPC's by dgscott**
KoboldFC Sheet: 
<https://docs.google.com/spreadsheets/d/1Qh_9h4T_ulKJjb6kU5wkrGB-tOKedm__FQn-L48frWk/edit?usp=sharing>
PDF Source: 
<https://drive.google.com/file/d/0BwKOfP0lLMsLTUdrQkhIamVyZlU/view>

**Comment by Asmor** [comment]
I've put links to these in the community content thread on reddit:

https://www.reddit.com/r/asmor/comments/9dpyxv/list_of_communityadded_kfc_content/e5osoda/
