### ISSUE TITLE
Into The Borderlands Monsters

### ISSUE THREAD

**Issue by ZookTDribit** [Asmor/5e-monsters#141]
I left most the environment as everything as it doesn't specify in the book and I didn't want to limit them without really looking into them.  Otherwise here is the monster appendix for Into the Borderlands 5e conversion, 49 monsters and unique variants. 

https://docs.google.com/spreadsheets/d/1NwjJS2Jpf_CxCZtHRCIJxc-6rERIo9vbFSqcs5ttE8M/edit#gid=0

**Comment by Asmor** [comment]
I've posted this in the community content thread in reddit: https://www.reddit.com/r/asmor/comments/9dpyxv/list_of_communityadded_kfc_content/e5orwnz/
