### ISSUE TITLE
Problems with shareable links

### ISSUE THREAD

**Issue by Asmor** [Asmor/5e-monsters#150]
Two people on reddit have reported issues with the creature codex not showing up from the shareable links.

If you're having trouble please try the following...

1. Go back to [the shareable link for creature codex](http://kobold.club/5e-monsters/sheet-check.html?name=Creature%20Codex&sheetid=1xvsgQt8I52ZA4eFBu_zzQd6ahydMMn13Ii5CjoS1BuM) and click Add again. You should get a popup that says 'This sheet is already saved as "Creature Codex"'. Let me know if you don't.

2. Go to KFC and click Manage Content. You should see the Creature Codex sheet listed there. Let me know if you don't.

3. Click Set Sources. Creature Codex should be the second entry, right under Basic Rules v1.

**Comment by A-McMorine** [comment]
As requested from reddit.

When I open the sharable link and click the "add to KFC" button, it says that the content has been added and to refresh KFC to see it, but none of the new sources are showing up in the "set sources" menu. If I re-click add I get the message "This sheet is already saved as "Creature Codex"" but Creature Codex isn't showing up under Manage Content or Set Sources. I'm using Google Chrome. I refreshed the page normally and tried ctrl+f5, but neither did anything.

Screenshots:
![1](https://user-images.githubusercontent.com/39338189/45273597-6ef30000-b481-11e8-886c-971ecb4db44f.png)
![2](https://user-images.githubusercontent.com/39338189/45273598-6ef30000-b481-11e8-830e-50b6b3fd7b3a.png)
![3](https://user-images.githubusercontent.com/39338189/45273599-6ef30000-b481-11e8-9c29-a18008975b2f.png)
![4](https://user-images.githubusercontent.com/39338189/45273600-6ef30000-b481-11e8-82cb-caf3b606282a.png)
![5](https://user-images.githubusercontent.com/39338189/45273601-6ef30000-b481-11e8-8a34-5ebcdd468d36.png)

The output from that little snippet of code is "5em-custom-content,5em-filters,5em-party-info,5em-sheet-cache:1I5W-x8QOcP2siGCPIhWWzKGWt4vyBivYLbmkv_G1B24,5em-sheet-cache:1YR8NBDp8BP4Lz-CWChh6-8dOPN7aYV_dRD6g9ZBvNqM,5em-sheet-cache:1x6xC8fHZ6N6M2wOuwPTNdn0ObCPtdqeIBtXaLjHBMYQ,5em-sheet-meta"

**Comment by eerongal** [comment]
I have the same issue described above, on chrome as well. Steps are just like in the screen shots. Output of the console command:

"5em-custom-content,5em-filters,5em-library,5em-party-info,5em-sheet-cache:1I5W-x8QOcP2siGCPIhWWzKGWt4vyBivYLbmkv_G1B24,5em-sheet-cache:1YR8NBDp8BP4Lz-CWChh6-8dOPN7aYV_dRD6g9ZBvNqM,5em-sheet-cache:1x6xC8fHZ6N6M2wOuwPTNdn0ObCPtdqeIBtXaLjHBMYQ,5em-sheet-meta"

**Comment by Asmor** [comment]
I realized what the problem is. It's because you're visiting the sheet checker in non-secure HTTP, but you're using KFC in secure HTTPS. They're treated as different domains and have separate storage.

I'll need to figure out a better solution, but as a workaround for the time being just use this link instead: https://kobold.club/5e-monsters/sheet-check.html?name=Creature%20Codex&sheetid=1xvsgQt8I52ZA4eFBu_zzQd6ahydMMn13Ii5CjoS1BuM

**Comment by eerongal** [comment]
are you using cookies or indexddb to store this client side? if it's cookies, i believe its because one way is setting the cookie to "secured", which means it only works on HTTPs. If it's on indexeddb, i believe that's a feature, and not sure you can circumvent it.

**Comment by Asmor** [comment]
Created #151 to fix this; leaving this open for the time being in case others have the same problem and come looking here.

As a temporary bandaid, I've added a warning to the sheet checker that you need to match the version of KFC that you use, and a link to switch to the other version.

**Comment by Asmor** [comment]
@eerongal It's localStorage, and yeah, not sure the best way to address this. I've opened #151 to figure out a solution.

**Comment by eerongal** [comment]
@Asmor ah. Not too familiar with localstorage, so can't help much there. That said, i'd probably just force to HTTPS and call it a day myself

**Comment by Asmor** [comment]
Problem with that is the vast majority of users are using HTTP, and they'd lose everything if I just cut off access to it. I need to migrate the data over.

**Comment by Asmor** [comment]
Closing this out as it was troubleshooting a single user's issue and the broader problem is to be addressed in #151.
