### ISSUE TITLE
A way to select ideal number of monsters when randomizing.

### ISSUE THREAD

**Issue by JustJinxx** [Asmor/5e-monsters#157]
Sometimes when I am randomly making encounters I want to do a boss fight or something and would prefer to have a singular enemy randomized. I know this isn't always an option depending on player level and number of players but it would be a nice feature to have instead of repeatedly having to randomize over and over hoping to have one pop up.

**Comment by Asmor** [comment]
You can already randomize individual sets of monsters. Just pick any random monster of the CR you're looking for and randomize it.
