### ISSUE TITLE
Guildmaster's Guide

### ISSUE THREAD

**Issue by Campb3ll45** [Asmor/5e-monsters#159]
Do you plan on adding the monsters from Guildmaster's Guide to Ravnica? I have a group that just gave me the book as an early Christmas present and I like to t use KFC as my encounter generator because it does the math for me. Im simply asking because i went on and was looking for the cackler and other monsters that appear in the book, but was unable to find them or even the source from the "Set Sources" tab.

**Comment by Asmor** [comment]
I don't have any plans to myself and AFAICR no one is working on that at the moment.

**Comment by Asmor** [comment]
I've added it.

http://kobold.club/5e-monsters/sheet-check.html?name=Guildmasters%27%20Guide%20to%20Ravnica&sheetid=1XzwnUVRzHdXJMbLi5IFHeocSNWomId3vYATakRS7N7o

**Comment by sporeservant** [comment]
Not sure if you're aware, or if I am missing something, but Guildmaster's Guide to Ravnica doesn't show up when you go to the Set Sources menu. 

Of course, after running this import, it will show up, but it isn't available by default. Should it be?

**Comment by Asmor** [comment]
This is the correct behavior.
