### ISSUE TITLE
Feature Request - Random Monster Generator responds to filters in upper right

### ISSUE THREAD

**Issue by ahowl7mx** [Asmor/5e-monsters#166]
Nice tool, thanks much Asmor -
It would be great to have the random encounter respond to the selections in the filters in the upper right hand corner.  For example if I wanted to setup a difficult encounter for 4 level 9 characters, it would be nice to have each monster CR > 1 but <5, evil, forest, and with a theme (Undead, lizard/draconic, flying, aquatic, etc).  Even better if there were some sort of role balancing such as 1 mage or cleric equivalent.

Currently the random generator does not respond to the filter/list.  Thanks!

**Comment by Asmor** [comment]
It already does this and always has.
