### ISSUE TITLE
Zaratan Incorrect CR

### ISSUE THREAD

**Issue by Jinzuku** [Asmor/5e-monsters#169]
Zaratan's CR is stated to be 21 but in the Mordenkainen's Tome of Foes it's listed as 22.
![image](https://user-images.githubusercontent.com/49715063/56277548-773ca900-60fc-11e9-8557-565bed661758.png)
![image](https://user-images.githubusercontent.com/49715063/56277586-89b6e280-60fc-11e9-99c2-7df62b4f63c0.png)

**Comment by Asmor** [comment]
Thanks, this has been updated.
