### ISSUE TITLE
Running encounter in Improved Initiative, monsters have 1 HP

### ISSUE THREAD

**Issue by autoferrit** [Asmor/5e-monsters#171]
Whenever I send my encounter over to improved initiative, the HP always only have 1 HP. It should be either the average HP, or (if possible) let IM roll the hit points (probably not possible).

It should at least set the average HP.

![image](https://user-images.githubusercontent.com/89895/57588115-824ce400-74c4-11e9-8e1d-b4f14baf7702.png)

**Comment by elsoybean** [comment]
@autoferrit this doesn't happen for me either locally or on https://kobold.club/fight/. In both cases the rolled HP comes over to Improved Initiative for both the group (if chosen) and monsters. Is this still happening for you? Can you give me steps to reproduce?

**Comment by autoferrit** [comment]
I had realized this was because I changed a setting for setting the HP for creatures to use the average. Which ended up effecting them when imported from KFC. So it is more of a configuration setting. 

When making that change, there should be some comment stating that creatures being imported will do this.
