### ISSUE TITLE
You should add a pets section

### ISSUE THREAD

**Issue by RagingButter** [Asmor/5e-monsters#176]
You should add a pets section to help calculate the fights if people have pet panthers or other stuff.

**Comment by Asmor** [comment]
There are no rules for that, are there?

**Comment by RagingButter** [comment]
No and I am realizing that there is nothing that works for converting cr to player lvl

**Comment by chisaipete** [comment]
By pets, do you mean things like beast companion?

**Comment by RagingButter** [comment]
yes

**Comment by chisaipete** [comment]
I believe Beast Companion and other class features are already taken into account when the game's action economy is balanced around the adventurers.  For the purpose of Encounter Creation, I think it would be largely irrelevant to try and account for pets separately.

**Comment by RagingButter** [comment]
Ok

**Comment by Asmor** [comment]
@chisaipete is correct. Class features like animal companions and familiars are already included in the balancing of a class.

TY guys for working this out. :)
