### ISSUE TITLE
Issue with Buttons on Site

### ISSUE THREAD

**Issue by Lunos8** [Asmor/5e-monsters#187]
The "Set Sources", "Manage Content", and even "Clear Local Storage" buttons aren't working for me at all. I'm on Firefox and have already tried clearing my history and cache. I apologize if this is a simple fix, I'm honestly not great at these things. 

P.S. your site is a God send, especially for a new DM like myself.

**Comment by SeanCooney** [comment]
They're working for me on Firefox 74.0 on Windows 10. Is your Firefox up to
date? What OS are you using?

**Comment by Lunos8** [comment]
I'm using Firefox 74.0 as well, but using a Mac 10.14.6


    On Thursday, March 19, 2020, 4:18:29 PM EDT, SeanCooney <notifications@github.com> wrote:  
 
 

They're working for me on Firefox 74.0 on Windows 10. Is your Firefox up to
date? What OS are you using?

**Comment by Lunos8** [comment]
So I just updated my mac to 10.15.3 and it now all appears to be working correctly. Honestly happy that it was on my end. Thank you very much!

    On Thursday, March 19, 2020, 6:28:49 PM EDT, Jamie Neeley <nebakamelo@yahoo.com> wrote:  
 
  I'm using Firefox 74.0 as well, but using a Mac 10.14.6


    On Thursday, March 19, 2020, 4:18:29 PM EDT, SeanCooney <notifications@github.com> wrote:  
 
 

They're working for me on Firefox 74.0 on Windows 10. Is your Firefox up to
date? What OS are you using?
