### ISSUE TITLE
Add toggle for basing encounter generation/difficulty-display on "Total XP" instead of "Adjusted XP"

### ISSUE THREAD

**Issue by EMcG0402429** [Asmor/5e-monsters#188]
It would be nice if there were a toggle for basing encounter generation/difficulty-display on the DMG "Total XP" instead of the (so far as I can tell) KFC original "Adjusted XP". I'm using straight DMG rules, so having to do the manual conversion adds another step to every encounter made. To KFC's credit it does _display_ all the information required for that, but it's still a thing which could easily be made less troublesome.

Edit: To clarify, there's stuff like the single-monsters, which, per DMG, should have an x1 modifier, but seem to have an x0.5 in KFC. The enemy count multipliers for higher-numbers of stuff also seem to be slightly different. Hence the request for just being able to base it on Total.

**Comment by Asmor** [comment]
Read the DMG. Specifically the part about large groups.
