### ISSUE TITLE
Typos on creatures from Monsters of the Orient

### ISSUE THREAD

**Issue by TheMaskedTom** [Asmor/5e-monsters#195]
From the Monsters of the Orient (I have v.1.0, might be from a different version?).

For the Kyoso Spawn (Blood Serpent), the CR on KFC is 20, while in the pdf (p. 74) is 18.
The Ashu no Oni (Barbed Lurker) is actually Ashi no Oni (Barbed Lurker) (p.72).

Thanks for all the work.

**Comment by Asmor** [comment]
I've made this change. Thank you.
