### ISSUE TITLE
Error in Mummy Statblock

### ISSUE THREAD

**Issue by therobotmenace** [Asmor/5e-monsters#197]
The mummy statblock has an error. According to the Monster Manual the Mummy has damage resistance to bludgeoning, piercing, and slashing from nonmagical attacks, however the stablock within Kobold Fight Club lists it as having immunity to these damage types.

**Comment by Asmor** [comment]
KFC only has the most basic stats (level, CR, etc). You're probably looking for [Improved Initiative](https://www.improved-initiative.com/).
