### ISSUE TITLE
XP for Empyrean is incorrect

### ISSUE THREAD

**Issue by theroguelumberjack** [Asmor/5e-monsters#200]
The monster manual for the Empyrean has the XP value as 32,500. And it seems to track correctly for encounter difficulty, but shows (and calculates as) 50,000 when splitting out the XP to players.

![Screen Shot 2020-08-18 at 8 21 26 AM](https://user-images.githubusercontent.com/69855097/90518037-d9ac1c00-e12b-11ea-8a95-9f14e60c4ca0.png)

**Comment by Asmor** [comment]
This is correct. The book is wrong. See chart on page 9 in same book. Also, https://media.wizards.com/2015/downloads/dnd/MM_Errata.pdf

> Empyrean (p. 130). XP: 50,000 [was 32,500].
