### ISSUE TITLE
Tome of Beasts 2

### ISSUE THREAD

**Issue by Mormon63** [Asmor/5e-monsters#204]
I'd love to see the Tome of Beasts 2 by Kobold Press added to the list of third party books included. Are there plans for this?

**Comment by Asmor** [comment]
![image](https://user-images.githubusercontent.com/2127204/100529364-d3125380-31b4-11eb-81e3-465b8c52f775.png)

**Comment by Mormon63** [comment]
I have no idea how I'd even attempt to port it for you guys. I'd be willing to help support financially for such an undertaking, but I have no knowledge on how to do something like that.
