### ISSUE TITLE
Incorrect XP multiplication for 7+ creature encounters

### ISSUE THREAD

**Issue by crstoner** [Asmor/5e-monsters#205]
The XP multiplication for encounters of 7+ monsters is off by one stage as per the DMG. E.g. an encounter with 7 monsters has its XP multiplied by 2 instead of 2.5.

From the DMG:
# Monsters   Multiplier
1                   x1
2                   x1.5
3-6                x2
7-10              x2.5
11-14            x3
15+               x4

![image](https://user-images.githubusercontent.com/67440862/102706624-2aa65b00-4259-11eb-8a01-e7b3a1567ebc.png)

**Comment by Asmor** [comment]
It is working correctly, read the DMG.
