### ISSUE TITLE
Bug - Incorrect Modifier Used

### ISSUE THREAD

**Issue by FrankTrog** [Asmor/5e-monsters#209]
Thank you for providing this wonderful tool to the community!

Today, I watching over an encounter and someone pointed out that the xp awarded didn't match their calculator. Comparing 5etools encounter calculator to the kobold fight club it looks like it is doing a x2 modifier for one of the fights I watched. 

A lvl 11 and lvl 10 vs a minotaur skeleton (cr2) and a necromancer (cr9). The base xp is correct at 2,725 but the modified xp is incorrect. The modifier should be 1.5 for 2 monsters not 2 which is what it seems to be using instead. 

![Screenshot_12](https://user-images.githubusercontent.com/3493822/112638275-74cd4880-8e15-11eb-96ad-f49a4dc527a0.png)

**Comment by Asmor** [comment]
working correctly. Read the DMG.
