### ISSUE TITLE
kobold.club now redirects to thenicestplace.net, website nonfunctional

### ISSUE THREAD

**Issue by GeneralContactUnit** [Asmor/5e-monsters#224]
Kobold.club appears to be no more. All functions of this website appear to have been disabled. 

http://kobold.club/fight/#/encounter-builder 
redirects to 
https://thenicestplace.net/fight/#/encounter-builder

And gives the error: Apache/2.4.29 (Ubuntu) Server at thenicestplace.net Port 443

**Comment by Asmor** [comment]
Working as intended.

**Comment by GeneralContactUnit** [comment]
> Working as intended.

Permanently? Or is this some kind of temporary joke?

**Comment by SeanCooney** [comment]
Ian is no longer willing or able to maintain the website. Fortunately, he
open sourced the code and someone else is now hosting the website. It is
now hosted at https://koboldplus.club/#/encounter-builder

**Comment by Asmor** [comment]
> It is now hosted at ...

_One_ implementation of several is hosted there. There are many. I will not give preference or recommendation to any of KFC's successors.
