### ISSUE TITLE
Broken Encounter Builder in Chrome 54.0.2840.99 m

### ISSUE THREAD

**Issue by chisaipete** [Asmor/5e-monsters#24]
![image](https://cloud.githubusercontent.com/assets/458551/20467323/212ffae2-af3a-11e6-951a-d8167706836c.png)

Is there something I'm not doing in my browser to clear caches or something?  Ctrl+F5, deleting my cookies, everything...nothing seems to make it look correct.

**Comment by Asmor** [comment]
That's not good... I updated it so that this shouldn't happen.

You can fix it by clearing your cache (ctrl+shift+delete, might be command+shift+delete on mac?). You don't need to delete cookies, just clear cache

**Comment by jbarzilai** [comment]
Connor, is this something with the live site or your local build?

**Comment by chisaipete** [comment]
Live site, clearing the cache didn't do anything. Should be easy to reproduce by loading the site in Chrome.

**Comment by chisaipete** [comment]
Clearing the cache worked. I didn't want to have to clear everything, but alas, doing so instead of trying to clear the cache selectively was what made it work.
