### ISSUE TITLE
Latest update only works in Chrome's Incognito?

### ISSUE THREAD

**Issue by gotex007** [Asmor/5e-monsters#25]
For some reason, this new update to KFC doesn't work in Chrome unless I open it in Incognito. It's not an extension issue, as I disabled them all to check.

**Comment by Asmor** [comment]
Clear your cache.

**Comment by jbarzilai** [comment]
So we think this is related to Chrone aggressively caching some of the
various HTML pages we are pulling in via AJAX.  We tried putting in cache
busting, but it doesn't seem to be working.  If you clear your cache does
it start working for you?

I'm going to try to work on some more aggressive changes to fix the caching
issues tonight.

**Comment by gotex007** [comment]
Hmm. I was using ctrl-F5 and deemed that enough if it was a cache problem, but you were right.

Thank you for the expedient response.

**Comment by Asmor** [comment]
Thanks to @jbarzilai for giving me the idea of taking a look at the JS caching. That hadn't even occurred to me. I've now made it so that asynchronous JS files will be cache-busted. So hopefully now at most a hard reload should be sufficient.
