### ISSUE TITLE
Make selected encounter 'sticky'

### ISSUE THREAD

**Issue by Asmor** [Asmor/5e-monsters#26]
On wider resolutions where the encounter is shown to the left of the table of monsters, the encounter should remain visible when you scroll down.

I think the best solution here might be to put the table inside of a div with overflow:scroll. That way only the table scrolls. And as a bonus, this would also make it simple to keep the pagination controls and filters always visible.

**Comment by jbarzilai** [comment]
I agree.  I've actually added this and a ton of other feature requests to
my fork's issues (https://github.com/jbarzilai/5e-monsters/issues/8 in this
case) as I didn't want to pollute your repo with some of my TODOs and notes.

**Comment by Asmor** [comment]
Ah, groovy. Thanks.
