### ISSUE TITLE
Add dummy data to placeholders

### ISSUE THREAD

**Issue by oganm** [Asmor/5e-monsters#40]
As it stands since they have no AC, HP or initiative, it is not possible to modify a placeholder monsters' hp or keep track of it's initiative in the "run encounters" section. If dummy values were added (0 10 whatever), those could be modified when running the encounter to fit the needs.

https://github.com/Asmor/5e-monsters/blob/7bad71abb15f59f0b69efb88676979b6278fa1ad/scripts/data/monsters.js#L12-L45

**Comment by Asmor** [comment]
This is now resolved!
