### ISSUE TITLE
Incorrect difficulty for random encouter

### ISSUE THREAD

**Issue by gareththegeek** [Asmor/5e-monsters#46]
Using a party of 3 level 4 adventurers, if I filter the list of available monsters by entering 'Bandit' and then click random encounter, the result is always one difficulty below the requested difficulty.

For example if I generate a random Medium encounter, I get an Easy encounter.

If I clear the monster filter, I get the correct random encounter difficulty.

**Comment by Asmor** [comment]
There are only 3 entries with CRs of 1/8, 2, and 4 that contain the word "Bandit". The encounter generation simply doesn't work well without a good variety of creatures to pick from.
