### ISSUE TITLE
Overhaul environments

### ISSUE THREAD

**Issue by Asmor** [Asmor/5e-monsters#54]
When I started KFC, there were no environment tables for the monsters in the MM. As a result, I made up my own.

Those tables exist now, and other products also include environments. Should research what's out there and overhaul the data to bring it in line with official sources.

**Comment by hugomarques** [comment]
Kobold press released the Tome of Beasts monster by terrain some time ago if that helps.

https://koboldpress.com/kpstore/product/tome-of-beasts-for-5th-edition/

**Comment by Asmor** [comment]
Wow. Their store is atrocious. I literally couldn't click the checkout button on the item page. They had an animation that increased the size of the button, shunting it to the next line, so no matter what I did it always moved away from my cursor.

I did manage to check out by going to the cart page. x_x

Thanks, this will be helpful for my research

**Comment by Asmor** [comment]
Ugh. Quite a mess. Also, can't believe the official lists don't include aquatic.

* Tome of Beasts
	* Any
	* Aquatic
	* Badlands
	* Desert
	* Forests
	* Hills
	* Marshes
	* Mountains
	* Plains
	* Ruins & Underground
* Official (DMG & Volo's)
	* Arctic
	* Coastal
	* Desert
	* Forest
	* Grassland
	* Hill
	* Mountain
	* Swamp
	* Underdark
	* Urban
* Mine
	* aquatic
	* arctic
	* cave
	* coast
	* desert
	* dungeon
	* forest
	* grassland
	* mountain
	* planar
	* ruins
	* swamp
	* underground
	* urban

**Comment by hugomarques** [comment]
Cool, I'm glad that helped.

Let me know if you need help updating the change. I'll gladly give a pair of extra hands =)

**Comment by Asmor** [comment]
Ok, so I want to preface this by saying that there's a wide variety of natural biomes out there, and in many case I'm playing fast and loose with the definitions of them or combining fairly distinct biomes together.

The goal for environments is for a DM to be able to get a variety of monsters appropriate to whereever their players may be. This is best served by sticking to simple, iconic environments, and letting the DM handle cases where a monster might not make thematic sense (e.g. players are in a Death Valley-style desert and you roll a mummy).

Fortuitously, my list is actually pretty close to the official list, which is a good sign. The only major differences are that I have aquatic and planar, and official has hill. The other difference is that official has underdark, which is a bit setting-specific for my taste and I'm going to translate to the generic underground.

* Location guidelines
	* aquatic
		* Any monster which could reasonably be encountered underwater or at sea (or in the middle of a lake...). This is a fairly broad category.
	* arctic
		* Cold, snow-covered locations.
	* coast
		* Aquatic creatures which are also capable of functioning on land, or land creatures which are also capable of functioning in the water.
	* desert
		* Hot, dry, sandy locations. Yes, deserts can be cold too, but for the purposes of monster environments think Sahara, not Antarctica.
	* forest
		* I hope we all know what a forest is...
	* grassland
		* Temperate plains. Long sight-lines. May have trees, but in smaller clumps.
	* mountain
		* Again, hope we all know what a mountain is
	* planar
		* Catch all for creatures found on other planes. Inner planes, outer planes, transitive planes... Yeah, they're all wildly different, but this is heavily reliant on a campaign's cosmology, so just throw them all together and let god (i.e. DMs) sort 'em out.
	* swamp
		* Considering changing this to "wetlands", as a more inclusive term for more biomes, and also hopefully more clear about what sort of creatures should be found there.
	* underground
		* Self-explanatory.
	* urban
		* Self-explantory.

* Removing:
	* cave
		* Thinking about it, monsters that would be encountered in a cave should probably instead be listed as "underground" and/or "mountain".
	* dungeon
		* This one is ill-defined, as the contents of a dungeon vary wildly and almost anything would make sense in some sort of dungeon. I'd originally created this environment with "classic" monsters like the rust monster and gelatinous cube in mind, but I feel that was a mistake.
	* ruins
		* Similar case to dungeon. Not really clear what this should mean, and it probably makes more sense to use the terrain type where the ruins are located.

* Adding:
	* hills?
		* I'm actually not entirely sure what hills should mean. How do the monsters found in hills differ from those found in grasslands/plains? This is included in both ToB and the official lists, which is why I'm considering the addition.

* Example conversion guidelines:
	* Official
		* Underdark -> Underground
	* Tome of Beasts
		* Badlands -> Desert
		* Marches -> Swamps (or wetlands if I change it)
		* Ruins & Underground -> Underground

**Comment by Asmor** [comment]
After asking about it on reddit and thinking some more, I'm just going to integrate grasslands and hills together. I feel like the distinction is just too fine, and the best explanations I got was a mechanical one (hills tend to have more difficult creatures), which can be handled by KFC by setting CR constraints.

**Comment by Asmor** [comment]
Not sure why I never closed this... AFAICT this task is complete.
