### ISSUE TITLE
Overhaul source categories

### ISSUE THREAD

**Issue by Asmor** [Asmor/5e-monsters#55]
Currently the source categories are a confusing mess, and with the ability for people to add custom sources in #53 there should be a way for them to specify what their source is.

So I'm thinking add a new column to the Sources sheets, "type". Sources would be grouped by types. Types could be things like "Homebrew", "Adventures", "Official", "Third party", etc.

Allow people to select all/select none for each type of source, as well as doing so everything.

**Comment by Asmor** [comment]
Started a little on this in #53. Pared down the existing buttons to just 3; "Everything", "Core", "Nothing."

**Comment by snafuy** [comment]
I'd work on this, but I can't find an interface design that's clearly superior to the current one.

Maybe on/off toggle buttons that remember state? All / Rule Books / Extras / 3rd Party? 
But what should it do when someone changes an individual source checkbox?
Maybe pairs of on/off buttons, 8 total? Would it be worth the extra space?
Or maybe say "it's good enough now" and close the issue?

**Comment by jbarzilai** [comment]
I wonder if it fits better with a tags interface? But I don't know if it's
going to be much better.

**Comment by Asmor** [comment]
I was thinking something like this:

https://codepen.io/Asmor/full/pVpXyQ/

If everything or nothing is selected, the list would be collapsed by default. Clicking the header expands and collapses the list. Checking the header box enables or disables all the items underneath it. Or you can expand and select items individually.

**Comment by Asmor** [comment]
Completed in 13ac7a906009eaaaf48660a921693032cedba037
