### ISSUE TITLE
Monster quantity buttons overlap in mobile

### ISSUE THREAD

**Issue by Asmor** [Asmor/5e-monsters#60]
Via email:

On the encounter info manager portion, the first monster chosen will appear as normal but the + and - buttons to add more of the same monster is covered by the random encounter generator button. This is making it difficult to just add one more of the same monster.

**Comment by eepMoody** [comment]
@Asmor I was just looking into fixing, but it seems to not be an issue anymore. Can you confirm whether you still see it? Maybe it's a device-specific issue?

**Comment by snafuy** [comment]
It only happens when your screen is narrower than 400px, and the Random button doesn't fit on the same line as "Encounter Info".
I put a CSS fix demo at https://snafuy.github.io/5e-monsters
(also JS fix for Issue #66 )

**Comment by Asmor** [comment]
The fix for this is now live.
