### ISSUE TITLE
Incorrect Monster Types

### ISSUE THREAD

**Issue by Zenshi** [Asmor/5e-monsters#61]
I spotted two mobs that were listed as the incorrect type (when referenced against my copy of the latest version of the book).

Bastet Temple Cat is labeled as a Beast but is actually a Monstrosity.
Cikavak is labeled as a Beast but is actually a Fey.

**Comment by Asmor** [comment]
They're beasts in the PDF I have. I'll check the book when I get home to see if the book differs from the PDF.

**Comment by Asmor** [comment]
Book has them as you said. Looks like their types were errated, and the book is correct.

I've updated them. Thanks!
