### ISSUE TITLE
Misc Tome of Beasts Creature Errors/Errata

### ISSUE THREAD

**Issue by Zenshi** [Asmor/5e-monsters#62]
Zmey Headling is missing (Tome of Beasts p417) - also it should have the "forest, swamp" environments.

Also per the errata, there are a few type changes from what things currently are.

Clockwork Abomination is a "Fiend (Construct, Devil)" but should be a "Construct (Devil)".
Spawn of Arbeyach is an "Aberration" but should be a "Fiend (Devil)".
Map Mimic is an "Aberration" but should be a "Monstrosity".
Oculo Swarm is a "Monstrosity (Swarm)" but should be an "Aberration (Swarm)".

**Comment by Asmor** [comment]
Thanks, these have all been updated!
