### ISSUE TITLE
Capitalization of Alignment and Environment filter options. 

### ISSUE THREAD

**Issue by CyborgEric** [Asmor/5e-monsters#67]
Hello!  I am loving this tool as a brand new DM!   I would like to propose a quality of life fix, correcting the capitalization inconsistency for some filter options.  At least on mobile, specifically the Alignment and Environment filter strings (E.G. Neutral Good or Mountain) are all lower case whereas the Size and Type filters are all capitalized. 

I am a student webdev finishing a billion projects presently or I would try to read up on the structure of this application. 

Thank you for this incredible tool!!! 

1) Reproduction (on mobile) :
2) Go to the home page
3) Click the drop down for "Any Alignment" 
4) View the capitalization of the options.

**Comment by Asmor** [comment]
Sizes and types are capitalized, alignments and environments are not. The filters are consistent with that.

> I am a student webdev finishing a billion projects presently or I would try to read up on the structure of this application.

Wow, holy crap, don't do that! This repo is awful! This was the second thing I ever built in Angular, and despite the efforts of some very talented contributors it's still a nasty hodgepodge of styles and techniques.
