### ISSUE TITLE
Unable to generate

### ISSUE THREAD

**Issue by jugslinger** [Asmor/5e-monsters#68]
First time user.

The site sounds like a great idea, but I am unable to use it. The website loads, but the generate button is stuck on "Random Medium." I have cleared my cache for firefox, and chrome. I also downloaded the git hub files, and tried running the index.html file.

![screenshot](https://cloud.githubusercontent.com/assets/10888401/26334393/8b09ed0a-3f19-11e7-916b-359c2b0a3ca5.png)

**Comment by Asmor** [comment]
There are no monsters in the content you have selected that match your filters (searching for "dragon").

Since dragon is such a common word, I'm guessing you don't have any sources enabled.

**Comment by jugslinger** [comment]
Coincidentally I can select sources now, before the list was blank. Sorry for the inconvenience.
