### ISSUE TITLE
Multiple Choice Selections

### ISSUE THREAD

**Issue by Zenshi** [Asmor/5e-monsters#69]
It'd be nice to move from an "All or Nothing" list style to a more "Multiple Choice" style. i.e. the ability to show both Monstrosities and Beasts without anything else. Also the ability to show Small, Medium, Large, without allowing Tiny, etc. Donjon's does something like this and I find it to be pretty helpful. It's also already done for the "Select Sources" dialog.

**Comment by Asmor** [comment]
This is now possible with regex searches, e.g. `/monstrosity|beast`
