### ISSUE TITLE
Monsters of the Orient

### ISSUE THREAD

**Issue by dnd5eoss** [Asmor/5e-monsters#75]
Hi KFC guys,

A little over a month ago I published a 5e bestiary on dmsguild.
It's a supplement to one of my previous titles, but the monsters within can really be used in any setting.
You can find the bestiary here: http://www.dmsguild.com/product/215595

I've put them all into the template for inclusion in KFC. 
You can find it here:
https://docs.google.com/spreadsheets/d/1Mt4u_lEkH3TPRQA8NdhiYa0TwS9QxQbxQESy3kdgPB8

If there are any errors just let me know, and I'll get it fixed.

Thank you guys for making and maintaining this awesome resource!

Sincerely,
Marc

**Comment by Asmor** [comment]
Thanks for the additions! I've added this to the third party collection, and it will show up if you refresh.
