### ISSUE TITLE
Derro Savant missing

### ISSUE THREAD

**Issue by malcyon** [Asmor/5e-monsters#76]
"Derro Savant" from pg. 225 of Out of the Abyss is missing. I tried adding it, but not sure it worked. No idea how to populate the gid field. 

https://docs.google.com/spreadsheets/d/1YwejYeXk0nDIewHLXI6-8qqB4WOllIO1BnAqKOpVVU0/edit?usp=sharing

**Comment by Asmor** [comment]
Thanks, I've added it!
