### ISSUE TITLE
Content is not there

### ISSUE THREAD

**Issue by Tomahawkbunny** [Asmor/5e-monsters#78]
I accessed Kobold Fight club for many months and found it very helpful, but in the past few weeks nothing has shown up on the sight, monster wise. I've tried resetting filterers, making sure I'd selected my sources, and re added content, but noting has worked. Please help.

**Comment by Asmor** [comment]
Please post a screenshot. I believe you can paste a screenshot directly into comments on here.

**Comment by Tomahawkbunny** [comment]
![image](https://user-images.githubusercontent.com/31808380/31319189-c2d74a72-ac2c-11e7-812e-ac0b261b378d.png)

**Comment by Asmor** [comment]
Click "Set sources". Make sure you have some of those checked.

**Comment by Tomahawkbunny** [comment]
![image](https://user-images.githubusercontent.com/31808380/31319306-d6dc56be-ac2e-11e7-9330-676c2f0ac1e1.png)

**Comment by Tomahawkbunny** [comment]
Still not working.

**Comment by Asmor** [comment]
Ok. That's weird.

Try clearing cache (ctrl+shift+delete) and then reloading.

If that doesn't work, go here: http://kobold.club/5e-monsters/help.html and then click the button that says "Clear local storage". That's a last resort, though, as it will also get rid of any data you've saved previously.

**Comment by RoadBlockActual** [comment]
I'm having the same issue on chrome, edge, firefox, and mobile chrome.  Clear local storage and clearing cache didn't resolve it.

**Comment by Asmor** [comment]
Thanks. I see the problem now and am investigating.

**Comment by Asmor** [comment]
Never mind, that was a false positive. What I thought was the problem isn't.

Are you getting any errors in your console? (F12, and select the tab that says "Console"). If so please send me a screenshot.

**Comment by RoadBlockActual** [comment]
thanks for the reply, looks like my work firewall may be blocking the
Google spreadsheet with the data. likely that's also what's happening with
mobile chrome, but i can't bring up the console to check

**Comment by Asmor** [comment]
Weird that your work would be blocking google sheets, but that would absolutely explain the problem.
