### ISSUE TITLE
Windows 10 - Chrome Browser - Site not updating

### ISSUE THREAD

**Issue by tezrak** [Asmor/5e-monsters#79]
Ever since I started using kobold.club in Chrome I've had no issues. Today, however, the "Deadly Medium" button will not autopopulate the encounter, and I cannot change it to a different difficulty. In Firefox, however, it works fine.

**Comment by Asmor** [comment]
Check that you're not filtering anything and you've got some sources turned on.

Also, try clearing your cache (ctrl+shift+delete, make sure "cached images and files" is checked).

If it still doesn't work, click the button on this page to clear your localstorage: http://kobold.club/5e-monsters/help.html

**Comment by tezrak** [comment]
Clearing localstorage seems to have done the trick. Thanks!
