### ISSUE TITLE
Adding monsters content from Ultimate Bestiary: Revenge of the Horde

### ISSUE THREAD

**Issue by Archi-Eremin** [Asmor/5e-monsters#83]
I'm gonna take a crack at putting a book into the spreadsheet, since my group uses it for enemies and using arcana.io is getting old, good as it is.

**Comment by Archi-Eremin** [comment]
So I finished typing it up and I've checked it. Here's the link:
https://docs.google.com/spreadsheets/d/18wk8uNUlu2JGZbWluGhgJ8CPxrmq8FFPsb29pxJrLgU/edit#gid=0

**Comment by Asmor** [comment]
Thanks, I've added it to the master third-party list!

**Comment by Archi-Eremin** [comment]
Turns out I forgot to add the monsters from appendix A: Beasts of the Horde. Here's the update:
https://docs.google.com/spreadsheets/d/1YSqwW6FWdeTyoBuZwpD5LwuEoJAH6BRDydEcetZ2avY/edit?usp=sharing
