### ISSUE TITLE
Missing "Hemogoblin" from Monster-A-Day Day 25

### ISSUE THREAD

**Issue by SirSodeez** [Asmor/5e-monsters#86]
https://www.reddit.com/r/monsteraday/comments/62n770/day_25_hemogoblin/

I've tried resetting sources, adding and removing sources (including Monster-A-Day), changing up CR values to narrow down the search, removing all values except sources and typing "goblin" "hemo" and other variations.

I'm also not sure if you are able to keep all Monster-A-Day creatures on Kobold FC but if you do, this one is missing.

**Comment by olavmueller** [comment]
The Monster a Day Compendium (which is the source included in KFC) ist the collection of monsters done by /u/StoneStrix from that reddit. No other monster since then has been included.

**Comment by Asmor** [comment]
That's just what the person who compiled the info provided. Assuming that subreddit is still active, if someone wanted to compile updates since then I'd be happy to add them.
