### ISSUE TITLE
New filter option: Add a filter for Legendary Creatures

### ISSUE THREAD

**Issue by datajack-dev** [Asmor/5e-monsters#87]
It would be great to filter the monster list to only show legendary creatures for solo encounter building.

**Comment by chisaipete** [comment]
Do you mean show only creatures with legendary actions?

**Comment by datajack-dev** [comment]
Yes. Xanathers guide has a new CR table for solo encounters and a new system for generating encounters. The book calls these solo creatures legendary creatures. Creatures with legendary actions are basically bosses. So adding a filter for these would make creating boss encounters much easier. I suggest you look at the solo encounter table in xanathers guide as it give CR ratings for groups by level. For example the table recommends a CR 8 legendary creature vs 4 5th level characters.


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Connor Petersen <notifications@github.com> Date: 11/16/17  4:50 PM  (GMT-05:00) To: Asmor/5e-monsters <5e-monsters@noreply.github.com> Cc: Cybertroll-xx <datajack@bellsouth.net>, Author <author@noreply.github.com> Subject: Re: [Asmor/5e-monsters] New filter option: Add a filter for Legendary
  Creatures (#87) 
Do you mean show only creatures with legendary actions?



On Thu, Nov 16, 2017 at 1:41 PM Cybertroll-xx <notifications@github.com>

wrote:

**Comment by Asmor** [comment]
Good idea. Although what I may end up doing is just making it so you can search for "legendary"

**Comment by datajack-dev** [comment]
That'll work :)

Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Ian Toltz <notifications@github.com> Date: 11/16/17  7:55 PM  (GMT-05:00) To: Asmor/5e-monsters <5e-monsters@noreply.github.com> Cc: Cybertroll-xx <datajack@bellsouth.net>, Author <author@noreply.github.com> Subject: Re: [Asmor/5e-monsters] New filter option: Add a filter for Legendary
  Creatures (#87) 
Good idea. Although what I may end up doing is just making it so you can search for "legendary"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Asmor/5e-monsters","title":"Asmor/5e-monsters","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Asmor/5e-monsters"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Asmor in #87: Good idea. Although what I may end up doing is just making it so you can search for \"legendary\""}],"action":{"name":"View Issue","url":"https://github.com/Asmor/5e-monsters/issues/87#issuecomment-345112096"}}}
