### ISSUE TITLE
New monsters: the tortle package

### ISSUE THREAD

**Issue by Daedalline** [Asmor/5e-monsters#88]
Hello,

I'm not sure if you want to add these, but in case you do here are the three new monsters from the WOTC web supplement: The Tortle Package.
https://docs.google.com/spreadsheets/d/1fIF_7onOYrltTvBoYfGjU635X2VTGJsH_19etOO8EYE

(package is here: http://www.dmsguild.com/product/221716/Tortle-Package-5e)

-Daedalline.

**Comment by Asmor** [comment]
I've requested access to the document. I only need view permission. (there are two different ways to share the sheets; it looks like you've shared it correctly for integrating with KFC, but that doesn't actually make it viewable directly by other people)

Also not entirely sure what to do with this... I have no problem adding it, but it feels like it's in a weird spot. Not third party, but it also... doesn't really feel official. I dunno. I'll figure out something.

**Comment by Asmor** [comment]
Ok, it's live. I forgot that "official web supplement" was one of the categories. >_>

**Comment by Daedalline** [comment]
I'm fine if you don't want to include it. It is a bit of an oddball. It was mostly just an experiment to learn how to import custom monster spreadsheets.

**Comment by Asmor** [comment]
You did perfectly. :)

Closing this out since it's live.
