### ISSUE TITLE
Monsters from Tomb of Annihilation

### ISSUE THREAD

**Issue by ghost** [Asmor/5e-monsters#89]
Here is the sheet I put together for the new monsters from Tomb of Annihilation.

https://docs.google.com/spreadsheets/d/1K79MabCYoQgr9sSjBEE1YRBxTgnj6GhuAjNbZo1M2Yw/edit#gid=0

* I wasn't sure how to populate the environments column...
* There are also reprints of certain stat blocks from Volo's that I put in a third tab with the new page numbers for updating those entries if you'd like.

**Comment by Asmor** [comment]
Thanks! I've thrown the new stuff in. Leaving this issue open until I get a chance to go back and update the page numbers for the monsters that overlapped with Volo's guide (thanks for doing that, btw!)

**Comment by ghost** [comment]
My pleasure!

**Comment by Asmor** [comment]
Finally got these all merged. Man, that's annoying. I've gotta find a better way to handle adding sources...

Thanks again for your work!
