### ISSUE TITLE
A number of Humanoids from Princes of the Apocalypse showing as Elemental

### ISSUE THREAD

**Issue by Smashman** [Asmor/5e-monsters#94]
Hi, I just noticed that Wiggan Nettlebee is showing as an Elemental. I confirmed and his stat block should state Humanoid.

I checked, and it appears that all of the 'Other Villians' stat blocks from the book are incorrectly showing as Elemental.

- [Drannin Splithelm](https://docs.google.com/spreadsheets/d/1I5W-x8QOcP2siGCPIhWWzKGWt4vyBivYLbmkv_G1B24/edit#gid=0&range=F41)
- [Ghald](https://docs.google.com/spreadsheets/d/1I5W-x8QOcP2siGCPIhWWzKGWt4vyBivYLbmkv_G1B24/edit#gid=0&range=F52)
- [Oreioth](https://docs.google.com/spreadsheets/d/1I5W-x8QOcP2siGCPIhWWzKGWt4vyBivYLbmkv_G1B24/edit#gid=0&range=F64)
- [Wiggan Nettlebee](https://docs.google.com/spreadsheets/d/1I5W-x8QOcP2siGCPIhWWzKGWt4vyBivYLbmkv_G1B24/edit#gid=0&range=F74)

Thanks.

**Comment by Asmor** [comment]
Thanks, these have been fixed.
