### ISSUE TITLE
KFC has no content

### ISSUE THREAD

**Issue by SomeCubingNerd** [Asmor/5e-monsters#96]
![screen shot 2018-01-22 at 4 22 18 pm](https://user-images.githubusercontent.com/31724873/35206417-a28fb422-ff90-11e7-99e2-14cef337073f.png)
No matter what happens Nothing turns up on the page. No other posts have the answer.What is going on?

**Comment by chisaipete** [comment]
Do you have any sources set?

**Comment by Asmor** [comment]
Does this link work for you?

https://docs.google.com/spreadsheets/d/1I5W-x8QOcP2siGCPIhWWzKGWt4vyBivYLbmkv_G1B24/edit#gid=0

Assuming so, click Manage Content and make sure you've got something in there selected.

**Comment by SomeCubingNerd** [comment]
![screen shot 2018-01-23 at 1 22 23 am](https://user-images.githubusercontent.com/31724873/35225253-eb32d42a-ffdb-11e7-8b2c-aec529cfe443.png)
The problem persists. I can see the google sheet, and the manage content window has appropriate data sets. Still nothing?

**Comment by Asmor** [comment]
Sorry, I meant set sources, not manage content. my bad.

**Comment by SomeCubingNerd** [comment]
![screen shot 2018-01-23 at 1 46 53 am](https://user-images.githubusercontent.com/31724873/35226435-69d284d0-ffdf-11e7-9049-02a3980c0ccc.png)
Sorry to bother you again but Even wen selected It does nothing. I can't select or unselect them.

**Comment by Asmor** [comment]
Do you have any JavaScript errors? (to check, in Chrome or Firefox, hit F12 and that will open the developer tools. Click the "console" tab and reload the page. Nothing should appear in that tab. If anything appears, please paste it here.

**Comment by SomeCubingNerd** [comment]
Failed to load resource: the server responded with a status of 403 ()
spreadsheets.google.com/feeds/worksheets/1YR8NBDp8BP4Lz-CWChh6-8dOPN7aYV_dRD6g9ZBvNqM/public/full?alt=json-in-script&callback=__jsonpcallback1 Failed to load resource: the server responded with a status of 403 ()
spreadsheets.google.com/feeds/worksheets/1x6xC8fHZ6N6M2wOuwPTNdn0ObCPtdqeIBtXaLjHBMYQ/public/full?alt=json-in-script&callback=__jsonpcallback2 Failed to load resource: the server responded with a status of 403 ()
angular.js:14110 TypeError: Cannot read property 'slice' of undefined
    at Object.getShuffledMonsterList (app-9ec9c5a732.js:2606)
    at getBestMonster (app-9ec9c5a732.js:2662)
    at Object.getRandomEncounter (app-9ec9c5a732.js:2592)
    at Object.generateRandom (app-9ec9c5a732.js:1780)
    at CurrentEncounterController.generateRandom (app-9ec9c5a732.js:373)
    at fn (eval at compile (angular.js:15033), <anonymous>:4:264)
    at expensiveCheckFn (angular.js:16123)
    at callback (angular.js:26490)
    at Scope.$eval (angular.js:17913)
    at Scope.$apply (angular.js:18013)
(anonymous) @ angular.js:14110

**Comment by Asmor** [comment]
Ok, so it _is_ a problem with loading the sheets. You're getting a 403 error (forbidden), which means that you're not allowed access.

What do you see if you go to this link? http://spreadsheets.google.com/feeds/worksheets/1YR8NBDp8BP4Lz-CWChh6-8dOPN7aYV_dRD6g9ZBvNqM/public/full?alt=json-in-script&callback=__jsonpcallback1

**Comment by SomeCubingNerd** [comment]
It says I need permission to view the document.

**Comment by SomeCubingNerd** [comment]
OHHHHH. I figured it out. My I'm a highschooler who uses my school email. Its probably blocked because of that. I signed into Chrome as a guest and It worked.

**Comment by Asmor** [comment]
Odd, as it allows anonymous access. Glad you got it figured out.

**Comment by SomeCubingNerd** [comment]
Thanks for the help!
